[general]
# Default resolution for FramePack is 640x640, but you can adjust.
resolution = [640, 640]
caption_extension = ".txt"
enable_bucket = true

[[datasets]]
  # This points to your training videos and their captions.
  video_directory = "framepack_dataset/videos_trimmed"
  
  # A separate cache directory is highly recommended.
  cache_directory = "framepack_cache"
  
  # Use 'full' extraction to train on entire video clips.
  frame_extraction = "full"
  
  max_frames = 129