# General settings that apply to all datasets unless overridden.
[general]
resolution = [960, 544]
enable_bucket = true
bucket_no_upscale = false

# --- Dataset Definition ---
# Each [[datasets]] block defines one dataset.
[[datasets]]
  # Use 'video_jsonl_file' for a video dataset described by a JSONL file.
  # Replace with the actual path to your metadata file.
  video_jsonl_file = "dataset/metadata.jsonl"

  # A cache directory is REQUIRED when using a JSONL file.
  # Create this directory if it doesn't exist.
  cache_directory = "cache"

  # Optional: Repeats the dataset 10 times per epoch. Good for smaller datasets.
  num_repeats = 10

  # Video-specific settings REQUIRED for HunyuanVideo.
  # The number of frames must be "N*4+1". Let's use 33 (8*4+1).
  target_frames = [33]

  # 'head' is the default and a good starting point. It takes the first 33 frames.
  frame_extraction = "head"