# dataset_config.toml
[general]
resolution = [640, 640]  # Default FramePack resolution. Adjust if your source videos are different.
frame_extraction = "full"
max_frames = 150 # ~5 seconds at 30fps. Set higher if your clips are longer.

[[datasets]]
[[datasets.subsets]]
type = "video"
video_dir = "framepack_dataset/videos"
caption_extension = ".txt"
num_repeats = 10 # Train more on each video